[package]
name = "guixu-operations"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
guixu-domain = { path = "../guixu-domain" }
guixu-platform = { path = "../guixu-platform" }
guixu-storage = { path = "../guixu-storage" }
thiserror.workspace = true
blake3.workspace = true
libc.workspace = true

[dev-dependencies]
tempfile = "3"
